include_role 'base'

include_cookbook 'yabai'
include_cookbook 'rbenv'
include_cookbook 'nodenv'
include_cookbook 'go'
include_cookbook 'vscode'
include_cookbook 'shottr'
include_cookbook '1password-cli'
include_cookbook '1password'
include_cookbook 'rubymine'
include_cookbook 'meetingbar'
