version: "1"
git_protocol: ssh
editor: !!null vim
prompt: enabled
pager:
aliases:
    co: pr checkout
    r: repo view --web
    v: pr view --web
    c: pr create --fill --draft --assignee @me
http_unix_socket:
browser:
