alias v='LANG=C nvim'
alias so='source'
alias ...='cd ../..'
alias gosrc='cd ~/go/src/'
alias ls='exa -l -a'
alias valec='AWS_SDK_LOAD_CONFIG=1 valec'
alias mkdir='mkdir -p'

alias gs='git status'
alias gb='git branch'
alias gc='git checkout'
alias gctm='git commit -m'
alias ga='git add'
alias gd='git diff'
alias gl='git log'
alias gcma='git checkout master'
alias gfo='git fetch origin'
alias gmom='git merge origin/master'
alias gpom='git push origin HEAD'
