alias v='nvim'
alias g='git'
alias tf='terraform'
alias re='source ~/.zshrc'
alias mkdir='mkdir -p'
alias ls='ls -l -a --color -i -p'
alias fd='fd -H'
alias valec='AWS_SDK_LOAD_CONFIG=1 valec'
alias lg='lazygit'
alias cl='claude'
alias cld='claude --dangerously-skip-permissions'
alias codex='codex --yolo'
